version: "2.4"
services:
  server:
    build: ./
    volumes:
      - ./src/:/src
    command: python3 -u /src/server.py
    environment:
      - MYID=${MYID}
      - BEARER=${BEARER}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "81:80"
    mem_limit: 50m
    cpus: '0.25'

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - "./mongo-volume:/data/db"
    ports:
      - "27017:27017"