version: "3.3"
services:
  server:
    build: ./
    volumes:
      - ./src/:/src
    command: python3 -u /src/server.py
    environment:
      - MYID=
      - BEARER=
    ports:
      - "81:80"

  mongo:
    image: mongo
    volumes:
      - "./mongo-volume:/data/db"
    ports:
      - "27017:27017"