version: '2'
services:
  server:
    working_dir: /src
    command: python3 -u jeopardy.py
    environment:
      - MYID=${MYID}
      - BEARER=${BEARER}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    mem_limit: 250m
    restart: always

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - "./mongo-volume:/data/db"
    ports:
      - "27017:27017"