service:
  name: JeopardyBot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  Jeopardy:
    handler: src/handler.main
    events:
      - http:
          path: message
          method: post